# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1592, 950)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(40, 60, 70);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.up_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.up_frame.sizePolicy().hasHeightForWidth())
        self.up_frame.setSizePolicy(sizePolicy)
        self.up_frame.setStyleSheet("color: rgb(255, 255, 255);")
        self.up_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.up_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.up_frame.setObjectName("up_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.up_frame)
        self.verticalLayout_3.setContentsMargins(0, 25, 0, 10)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.logo_label = QtWidgets.QLabel(self.up_frame)
        self.logo_label.setMinimumSize(QtCore.QSize(288, 216))
        self.logo_label.setMaximumSize(QtCore.QSize(288, 216))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap(":/logo/images/dsi_logo_background.png"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.verticalLayout_3.addWidget(self.logo_label, 0, QtCore.Qt.AlignHCenter)
        self.title_label = QtWidgets.QLabel(self.up_frame)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.verticalLayout_3.addWidget(self.title_label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.up_frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.down_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.down_frame.sizePolicy().hasHeightForWidth())
        self.down_frame.setSizePolicy(sizePolicy)
        self.down_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.down_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.down_frame.setObjectName("down_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.down_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 50)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.internet_card = QtWidgets.QFrame(self.down_frame)
        self.internet_card.setMinimumSize(QtCore.QSize(380, 0))
        self.internet_card.setMaximumSize(QtCore.QSize(380, 16777215))
        self.internet_card.setStyleSheet("#internet_card {\n"
"    border: 10px solid red;\n"
"    border-radius: 70px;\n"
"    padding: 10px;\n"
"}")
        self.internet_card.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.internet_card.setFrameShadow(QtWidgets.QFrame.Raised)
        self.internet_card.setObjectName("internet_card")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.internet_card)
        self.verticalLayout_4.setContentsMargins(50, 20, 50, 20)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.internet_logo = QtWidgets.QLabel(self.internet_card)
        self.internet_logo.setMinimumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.internet_logo.setFont(font)
        self.internet_logo.setStyleSheet("background-color: none;")
        self.internet_logo.setText("")
        self.internet_logo.setPixmap(QtGui.QPixmap(":/logo/images/wifi.png"))
        self.internet_logo.setScaledContents(True)
        self.internet_logo.setObjectName("internet_logo")
        self.verticalLayout_4.addWidget(self.internet_logo, 0, QtCore.Qt.AlignHCenter)
        self.internet_isim = QtWidgets.QLabel(self.internet_card)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.internet_isim.setFont(font)
        self.internet_isim.setStyleSheet("color: white;\n"
"background-color: none;")
        self.internet_isim.setObjectName("internet_isim")
        self.verticalLayout_4.addWidget(self.internet_isim, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.internet_check_frame = QtWidgets.QFrame(self.internet_card)
        self.internet_check_frame.setStyleSheet("color: rgb(158, 158, 158);\n"
"background-color: none;")
        self.internet_check_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.internet_check_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.internet_check_frame.setObjectName("internet_check_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.internet_check_frame)
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, 85)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.internet_check_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.internet_check = QtWidgets.QLabel(self.internet_check_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.internet_check.setFont(font)
        self.internet_check.setObjectName("internet_check")
        self.verticalLayout_5.addWidget(self.internet_check, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.internet_check_frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.internet_durum = QtWidgets.QLabel(self.internet_card)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.internet_durum.setFont(font)
        self.internet_durum.setStyleSheet("color: white;\n"
"background-color: none;")
        self.internet_durum.setObjectName("internet_durum")
        self.verticalLayout_4.addWidget(self.internet_durum, 0, QtCore.Qt.AlignHCenter)
        self.google_git = QtWidgets.QPushButton(self.internet_card)
        self.google_git.setMinimumSize(QtCore.QSize(150, 50))
        self.google_git.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.google_git.setFont(font)
        self.google_git.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.google_git.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 101, 98);\n"
"color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 162, 157);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    padding-top: 8px; \n"
"    padding-bottom: 6px;\n"
"}")
        self.google_git.setObjectName("google_git")
        self.verticalLayout_4.addWidget(self.google_git, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.internet_card, 0, QtCore.Qt.AlignHCenter)
        self.website_card = QtWidgets.QFrame(self.down_frame)
        self.website_card.setMinimumSize(QtCore.QSize(380, 0))
        self.website_card.setMaximumSize(QtCore.QSize(380, 16777215))
        self.website_card.setStyleSheet("#website_card {\n"
"    border: 10px solid red;\n"
"    border-radius: 70px;\n"
"    padding: 10px;\n"
"}")
        self.website_card.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.website_card.setFrameShadow(QtWidgets.QFrame.Raised)
        self.website_card.setObjectName("website_card")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.website_card)
        self.verticalLayout_7.setContentsMargins(30, 20, 30, 20)
        self.verticalLayout_7.setSpacing(20)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.website_logo = QtWidgets.QLabel(self.website_card)
        self.website_logo.setMinimumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.website_logo.setFont(font)
        self.website_logo.setText("")
        self.website_logo.setPixmap(QtGui.QPixmap(":/logo/images/website.png"))
        self.website_logo.setScaledContents(False)
        self.website_logo.setObjectName("website_logo")
        self.verticalLayout_7.addWidget(self.website_logo, 0, QtCore.Qt.AlignHCenter)
        self.website_isim = QtWidgets.QLabel(self.website_card)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.website_isim.setFont(font)
        self.website_isim.setStyleSheet("color: white;")
        self.website_isim.setObjectName("website_isim")
        self.verticalLayout_7.addWidget(self.website_isim, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.website_check_frame = QtWidgets.QFrame(self.website_card)
        self.website_check_frame.setStyleSheet("color: rgb(158, 158, 158)")
        self.website_check_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.website_check_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.website_check_frame.setObjectName("website_check_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.website_check_frame)
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, 85)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.website_check_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.website_check = QtWidgets.QLabel(self.website_check_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.website_check.setFont(font)
        self.website_check.setObjectName("website_check")
        self.verticalLayout_6.addWidget(self.website_check, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_7.addWidget(self.website_check_frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.website_durum = QtWidgets.QLabel(self.website_card)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.website_durum.sizePolicy().hasHeightForWidth())
        self.website_durum.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.website_durum.setFont(font)
        self.website_durum.setStyleSheet("color: white;")
        self.website_durum.setObjectName("website_durum")
        self.verticalLayout_7.addWidget(self.website_durum, 0, QtCore.Qt.AlignHCenter)
        self.website_button = QtWidgets.QPushButton(self.website_card)
        self.website_button.setMinimumSize(QtCore.QSize(150, 50))
        self.website_button.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.website_button.setFont(font)
        self.website_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.website_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 101, 98);\n"
"color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 162, 157);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    padding-top: 8px; \n"
"    padding-bottom: 6px;\n"
"}")
        self.website_button.setObjectName("website_button")
        self.verticalLayout_7.addWidget(self.website_button, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.website_card, 0, QtCore.Qt.AlignHCenter)
        self.b101_card = QtWidgets.QFrame(self.down_frame)
        self.b101_card.setMinimumSize(QtCore.QSize(380, 0))
        self.b101_card.setMaximumSize(QtCore.QSize(380, 16777215))
        self.b101_card.setStyleSheet("#b101_card {\n"
"    border: 10px solid red;\n"
"    border-radius: 70px;\n"
"    padding: 10px;\n"
"}")
        self.b101_card.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.b101_card.setFrameShadow(QtWidgets.QFrame.Raised)
        self.b101_card.setObjectName("b101_card")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.b101_card)
        self.verticalLayout_15.setContentsMargins(30, 20, 30, 20)
        self.verticalLayout_15.setSpacing(20)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.b101_logo = QtWidgets.QLabel(self.b101_card)
        self.b101_logo.setMinimumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.b101_logo.setFont(font)
        self.b101_logo.setText("")
        self.b101_logo.setPixmap(QtGui.QPixmap(":/logo/images/folder.png"))
        self.b101_logo.setScaledContents(False)
        self.b101_logo.setObjectName("b101_logo")
        self.verticalLayout_15.addWidget(self.b101_logo, 0, QtCore.Qt.AlignHCenter)
        self.b101_isim = QtWidgets.QLabel(self.b101_card)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b101_isim.setFont(font)
        self.b101_isim.setStyleSheet("color: white;")
        self.b101_isim.setObjectName("b101_isim")
        self.verticalLayout_15.addWidget(self.b101_isim, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.b101_check_frame = QtWidgets.QFrame(self.b101_card)
        self.b101_check_frame.setStyleSheet("color: rgb(158, 158, 158)")
        self.b101_check_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.b101_check_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.b101_check_frame.setObjectName("b101_check_frame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.b101_check_frame)
        self.verticalLayout_14.setContentsMargins(-1, 0, -1, 85)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_13 = QtWidgets.QLabel(self.b101_check_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_14.addWidget(self.label_13, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.b101_check = QtWidgets.QLabel(self.b101_check_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.b101_check.setFont(font)
        self.b101_check.setObjectName("b101_check")
        self.verticalLayout_14.addWidget(self.b101_check, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_15.addWidget(self.b101_check_frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.b101_durum = QtWidgets.QLabel(self.b101_card)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.b101_durum.setFont(font)
        self.b101_durum.setStyleSheet("color: white;")
        self.b101_durum.setObjectName("b101_durum")
        self.verticalLayout_15.addWidget(self.b101_durum, 0, QtCore.Qt.AlignHCenter)
        self.b101_button = QtWidgets.QPushButton(self.b101_card)
        self.b101_button.setMinimumSize(QtCore.QSize(150, 50))
        self.b101_button.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.b101_button.setFont(font)
        self.b101_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b101_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 101, 98);\n"
"color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 162, 157);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    padding-top: 8px; \n"
"    padding-bottom: 6px;\n"
"}")
        self.b101_button.setObjectName("b101_button")
        self.verticalLayout_15.addWidget(self.b101_button, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.b101_card)
        self.belgenet_card = QtWidgets.QFrame(self.down_frame)
        self.belgenet_card.setMinimumSize(QtCore.QSize(380, 0))
        self.belgenet_card.setMaximumSize(QtCore.QSize(380, 16777215))
        self.belgenet_card.setStyleSheet("#belgenet_card {\n"
"    border: 10px solid red;\n"
"    border-radius: 70px;\n"
"    padding: 10px;\n"
"}")
        self.belgenet_card.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.belgenet_card.setFrameShadow(QtWidgets.QFrame.Raised)
        self.belgenet_card.setObjectName("belgenet_card")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.belgenet_card)
        self.verticalLayout_17.setContentsMargins(30, 20, 30, 20)
        self.verticalLayout_17.setSpacing(20)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.belgenet_logo = QtWidgets.QLabel(self.belgenet_card)
        self.belgenet_logo.setMinimumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.belgenet_logo.setFont(font)
        self.belgenet_logo.setText("")
        self.belgenet_logo.setPixmap(QtGui.QPixmap(":/logo/images/belgenet.png"))
        self.belgenet_logo.setScaledContents(False)
        self.belgenet_logo.setObjectName("belgenet_logo")
        self.verticalLayout_17.addWidget(self.belgenet_logo, 0, QtCore.Qt.AlignHCenter)
        self.belgenet_isim = QtWidgets.QLabel(self.belgenet_card)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.belgenet_isim.setFont(font)
        self.belgenet_isim.setStyleSheet("color: white;")
        self.belgenet_isim.setObjectName("belgenet_isim")
        self.verticalLayout_17.addWidget(self.belgenet_isim, 0, QtCore.Qt.AlignHCenter)
        self.belgenet_check_frame = QtWidgets.QFrame(self.belgenet_card)
        self.belgenet_check_frame.setStyleSheet("color: rgb(158, 158, 158)")
        self.belgenet_check_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.belgenet_check_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.belgenet_check_frame.setObjectName("belgenet_check_frame")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.belgenet_check_frame)
        self.verticalLayout_16.setContentsMargins(-1, 0, -1, 85)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.belgenet_check_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_16.addWidget(self.label_15, 0, QtCore.Qt.AlignHCenter)
        self.belgenet_check = QtWidgets.QLabel(self.belgenet_check_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.belgenet_check.setFont(font)
        self.belgenet_check.setObjectName("belgenet_check")
        self.verticalLayout_16.addWidget(self.belgenet_check, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_17.addWidget(self.belgenet_check_frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.belgenet_durum = QtWidgets.QLabel(self.belgenet_card)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.belgenet_durum.setFont(font)
        self.belgenet_durum.setStyleSheet("color: white;")
        self.belgenet_durum.setObjectName("belgenet_durum")
        self.verticalLayout_17.addWidget(self.belgenet_durum, 0, QtCore.Qt.AlignHCenter)
        self.belgenet_button = QtWidgets.QPushButton(self.belgenet_card)
        self.belgenet_button.setMinimumSize(QtCore.QSize(150, 50))
        self.belgenet_button.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.belgenet_button.setFont(font)
        self.belgenet_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.belgenet_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 101, 98);\n"
"color: white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 162, 157);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    padding-top: 8px; \n"
"    padding-bottom: 6px;\n"
"}")
        self.belgenet_button.setObjectName("belgenet_button")
        self.verticalLayout_17.addWidget(self.belgenet_button, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.belgenet_card)
        self.verticalLayout_2.addWidget(self.down_frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.main_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "SİSTEM KONTROL"))
        self.internet_isim.setText(_translate("MainWindow", "İnternet"))
        self.label_2.setText(_translate("MainWindow", "---Son Kontrol---"))
        self.internet_check.setText(_translate("MainWindow", "00:00:00"))
        self.internet_durum.setText(_translate("MainWindow", "Durum: Çalışmıyor"))
        self.google_git.setText(_translate("MainWindow", "Git"))
        self.website_isim.setText(_translate("MainWindow", "DSİ Bursa"))
        self.label_3.setText(_translate("MainWindow", "---Son Kontrol---"))
        self.website_check.setText(_translate("MainWindow", "00:00:00"))
        self.website_durum.setText(_translate("MainWindow", "Durum: Çalışmıyor"))
        self.website_button.setText(_translate("MainWindow", "Git"))
        self.b101_isim.setText(_translate("MainWindow", "B101"))
        self.label_13.setText(_translate("MainWindow", "---Son Kontrol---"))
        self.b101_check.setText(_translate("MainWindow", "00:00:00"))
        self.b101_durum.setText(_translate("MainWindow", "Durum: Çalışmıyor"))
        self.b101_button.setText(_translate("MainWindow", "Git"))
        self.belgenet_isim.setText(_translate("MainWindow", "Belgenet"))
        self.label_15.setText(_translate("MainWindow", "---Son Kontrol---"))
        self.belgenet_check.setText(_translate("MainWindow", "00:00:00"))
        self.belgenet_durum.setText(_translate("MainWindow", "Durum: Çalışmıyor"))
        self.belgenet_button.setText(_translate("MainWindow", "Git"))

import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
